import type { Agent, DashboardData, DistrictInfo, Inquiry, Property, User } from '@/types';

const PHOTOS = {
  apt1: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
  apt2: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
  apt3: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
  house1: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
  house2: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
  comm1: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
  floorPlan: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80',
};

export const MOCK_USERS: User[] = [
  { id: 'u1', email: 'buyer@emlak.az', name: 'Leyla Məmmədova', role: 'BUYER', locale: 'AZ' },
  { id: 'u2', email: 'agent@emlak.az', name: 'Rəşad Həsənov', role: 'AGENT', locale: 'AZ', phone: '+994501234567' },
];

export const MOCK_AGENTS: Agent[] = [
  {
    id: 'a1',
    userId: 'u2',
    licenseNumber: 'AZ-2024-001',
    bioAz: '10 illik təcrübəli peşəkar agent. Bakının mərkəzi rayonlarında ixtisaslaşmışam.',
    bioEn: 'Professional agent with 10 years of experience specializing in central Baku districts.',
    bioRu: 'Профессиональный агент с 10-летним опытом, специализируюсь на центральных районах Баку.',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&q=80',
    isActive: true,
    user: MOCK_USERS[1],
  },
];

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'p1',
    titleAz: 'Nərimanovda premium 3 otaqlı mənzil',
    titleEn: 'Premium 3-room apartment in Narimanov',
    titleRu: 'Премиальная 3-комнатная квартира в Нарimanov',
    descriptionAz: 'Tam təmirli, geniş balkon, şəhər mənzərəsi. Nərimanov metrosuna 5 dəqiqəlik piyada məsafə. Bütün infrastruktur yaxınlıqdadır.',
    descriptionEn: 'Fully renovated, spacious balcony, city view. 5-minute walk to Narimanov metro. All infrastructure nearby.',
    descriptionRu: 'Полностью отремонтированная, просторный балкон, вид на город. 5 минут пешком до метро Нарimanov.',
    price: 285000,
    currency: 'AZN',
    listingType: 'SALE',
    propertyType: 'APARTMENT',
    rooms: 3,
    area: 98,
    floor: 8,
    totalFloors: 16,
    district: 'NARIMANOV',
    address: 'Nərimanov pr., 45',
    latitude: 40.4093,
    longitude: 49.8671,
    amenities: ['parking', 'elevator', 'security', 'balcony', 'heating'],
    photos: [PHOTOS.apt1, PHOTOS.apt2, PHOTOS.apt3],
    floorPlanUrl: PHOTOS.floorPlan,
    status: 'ACTIVE',
    ownerId: 'u1',
    agentId: 'a1',
    createdAt: '2025-06-01T10:00:00Z',
    updatedAt: '2025-06-20T10:00:00Z',
    agent: MOCK_AGENTS[0],
  },
  {
    id: 'p2',
    titleAz: 'Yasamaldakı müasir 2 otaqlı kirayə',
    titleEn: 'Modern 2-room rental in Yasamal',
    titleRu: 'Современная 2-комнатная аренда в Yasamal',
    descriptionAz: 'Yeni tikili, mebel ilə, istilik sistemi. Universitet yaxınlığında.',
    descriptionEn: 'New building, furnished, heating system. Near the university.',
    descriptionRu: 'Новостройка, меблированная, система отопления. Рядом с университетом.',
    price: 850,
    currency: 'AZN',
    listingType: 'RENT',
    propertyType: 'APARTMENT',
    rooms: 2,
    area: 65,
    floor: 5,
    totalFloors: 12,
    district: 'YASAMAL',
    address: 'H.Cavid pr., 112',
    latitude: 40.3872,
    longitude: 49.8322,
    amenities: ['elevator', 'furnished', 'heating', 'internet'],
    photos: [PHOTOS.apt2, PHOTOS.apt3],
    floorPlanUrl: PHOTOS.floorPlan,
    status: 'ACTIVE',
    ownerId: 'u1',
    agentId: 'a1',
    createdAt: '2025-06-05T10:00:00Z',
    updatedAt: '2025-06-18T10:00:00Z',
    agent: MOCK_AGENTS[0],
  },
  {
    id: 'p3',
    titleAz: 'Xətai rayonunda lüks villa',
    titleEn: 'Luxury villa in Khatai district',
    titleRu: 'Роскошная вилла в районе Khatai',
    descriptionAz: '500 m² sahə, hovuz, bağ, 5 otaq. Premium yaşayış kompleksində.',
    descriptionEn: '500 m² area, pool, garden, 5 rooms. In a premium residential complex.',
    descriptionRu: '500 м² площадь, бассейн, сад, 5 комнат. В премиальном жилом комплексе.',
    price: 1250000,
    currency: 'AZN',
    listingType: 'SALE',
    propertyType: 'HOUSE',
    rooms: 5,
    area: 500,
    floor: 2,
    totalFloors: 2,
    district: 'XETAI',
    address: 'Xətai pr., 78',
    latitude: 40.3733,
    longitude: 49.8603,
    amenities: ['pool', 'garden', 'parking', 'security', 'smart_home'],
    photos: [PHOTOS.house1, PHOTOS.house2],
    status: 'ACTIVE',
    ownerId: 'u1',
    agentId: 'a1',
    createdAt: '2025-06-10T10:00:00Z',
    updatedAt: '2025-06-22T10:00:00Z',
    agent: MOCK_AGENTS[0],
  },
  {
    id: 'p4',
    titleAz: 'Səbaildə dəniz mənzərəli penthaus',
    titleEn: 'Sea-view penthouse in Sabail',
    titleRu: 'Пентхаус с видом на море в Sabail',
    descriptionAz: 'Bulvar yaxınlığında, panoramik dəniz mənzərəsi, premium interyer.',
    descriptionEn: 'Near the boulevard, panoramic sea view, premium interior.',
    descriptionRu: 'Рядом с бульваром, панорамный вид на море, премиальный интерьер.',
    price: 950000,
    currency: 'AZN',
    listingType: 'SALE',
    propertyType: 'APARTMENT',
    rooms: 4,
    area: 185,
    floor: 22,
    totalFloors: 22,
    district: 'SEBAIL',
    address: 'Neftçilər pr., 153',
    latitude: 40.3589,
    longitude: 49.8364,
    amenities: ['sea_view', 'elevator', 'parking', 'security', 'gym'],
    photos: [PHOTOS.apt3, PHOTOS.apt1],
    floorPlanUrl: PHOTOS.floorPlan,
    status: 'ACTIVE',
    ownerId: 'u1',
    agentId: 'a1',
    createdAt: '2025-06-12T10:00:00Z',
    updatedAt: '2025-06-23T10:00:00Z',
    agent: MOCK_AGENTS[0],
  },
  {
    id: 'p5',
    titleAz: 'Badamdarda bağ evi',
    titleEn: 'Garden house in Badamdar',
    titleRu: 'Дом с садом в Badamdar',
    descriptionAz: 'Sakit məhəllə, geniş həyət, 3 otaq. Dənizə yaxın.',
    descriptionEn: 'Quiet neighborhood, large yard, 3 rooms. Close to the sea.',
    descriptionRu: 'Тихий район, большой двор, 3 комнаты. Близко к морю.',
    price: 420000,
    currency: 'AZN',
    listingType: 'SALE',
    propertyType: 'HOUSE',
    rooms: 3,
    area: 220,
    district: 'BADAMDAR',
    address: 'Badamdar şosesi, 34',
    latitude: 40.3522,
    longitude: 49.8122,
    amenities: ['garden', 'parking', 'terrace'],
    photos: [PHOTOS.house2, PHOTOS.house1],
    status: 'ACTIVE',
    ownerId: 'u1',
    agentId: 'a1',
    createdAt: '2025-06-15T10:00:00Z',
    updatedAt: '2025-06-24T10:00:00Z',
    agent: MOCK_AGENTS[0],
  },
  {
    id: 'p6',
    titleAz: 'Gəncədə yeni tikili mənzil',
    titleEn: 'New building apartment in Ganja',
    titleRu: 'Квартира в новостройке в Ganja',
    descriptionAz: 'Gəncə şəhər mərkəzində, 2 otaqlı, sərfəli qiymət.',
    descriptionEn: 'In Ganja city center, 2 rooms, affordable price.',
    descriptionRu: 'В центре Гянджи, 2 комнаты, доступная цена.',
    price: 95000,
    currency: 'AZN',
    listingType: 'SALE',
    propertyType: 'APARTMENT',
    rooms: 2,
    area: 72,
    floor: 3,
    totalFloors: 9,
    district: 'GENCE',
    address: 'Atatürk pr., 56',
    latitude: 40.6828,
    longitude: 46.3606,
    amenities: ['elevator', 'parking', 'heating'],
    photos: [PHOTOS.apt1, PHOTOS.apt2],
    floorPlanUrl: PHOTOS.floorPlan,
    status: 'ACTIVE',
    ownerId: 'u1',
    agentId: 'a1',
    createdAt: '2025-06-18T10:00:00Z',
    updatedAt: '2025-06-25T10:00:00Z',
    agent: MOCK_AGENTS[0],
  },
  {
    id: 'p7',
    titleAz: 'Nərimanovda ofis sahəsi',
    titleEn: 'Office space in Narimanov',
    titleRu: 'Офисное помещение в Нarimanov',
    descriptionAz: 'Biznes mərkəzində, 120 m², hazır ofis.',
    descriptionEn: 'In business center, 120 m², ready office.',
    descriptionRu: 'В бизнес-центре, 120 м², готовый офис.',
    price: 3500,
    currency: 'AZN',
    listingType: 'RENT',
    propertyType: 'COMMERCIAL',
    rooms: 0,
    area: 120,
    floor: 4,
    totalFloors: 10,
    district: 'NARIMANOV',
    address: 'Təbriz küç., 89',
    latitude: 40.4055,
    longitude: 49.8699,
    amenities: ['parking', 'elevator', 'security', 'internet'],
    photos: [PHOTOS.comm1],
    status: 'ACTIVE',
    ownerId: 'u1',
    agentId: 'a1',
    createdAt: '2025-06-20T10:00:00Z',
    updatedAt: '2025-06-25T10:00:00Z',
    agent: MOCK_AGENTS[0],
  },
  {
    id: 'p8',
    titleAz: 'Yasamaldakı torpaq sahəsi',
    titleEn: 'Land plot in Yasamal',
    titleRu: 'Земельный участок в Yasamal',
    descriptionAz: 'Tikinti üçün uyğun, 800 m², bütün kommunikasiyalar.',
    descriptionEn: 'Suitable for construction, 800 m², all utilities.',
    descriptionRu: 'Подходит для строительства, 800 м², все коммуникации.',
    price: 180000,
    currency: 'AZN',
    listingType: 'SALE',
    propertyType: 'LAND',
    rooms: 0,
    area: 800,
    district: 'YASAMAL',
    address: 'Yasamal q.',
    latitude: 40.3911,
    longitude: 49.8288,
    amenities: ['utilities'],
    photos: [PHOTOS.house1],
    status: 'ACTIVE',
    ownerId: 'u1',
    agentId: 'a1',
    createdAt: '2025-06-22T10:00:00Z',
    updatedAt: '2025-06-25T10:00:00Z',
    agent: MOCK_AGENTS[0],
  },
];

export const MOCK_DISTRICTS: DistrictInfo[] = [
  { id: 'NARIMANOV', slug: 'narimanov', nameAz: 'Nərimanov', nameEn: 'Narimanov', nameRu: 'Нарimanов', city: 'Baku', listingCount: 2, avgPrice: 285000 },
  { id: 'YASAMAL', slug: 'yasamal', nameAz: 'Yasamal', nameEn: 'Yasamal', nameRu: 'Ясамаль', city: 'Baku', listingCount: 2, avgPrice: 132500 },
  { id: 'XETAI', slug: 'xetai', nameAz: 'Xətai', nameEn: 'Khatai', nameRu: 'Хатаи', city: 'Baku', listingCount: 1, avgPrice: 1250000 },
  { id: 'SEBAIL', slug: 'sebail', nameAz: 'Səbail', nameEn: 'Sabail', nameRu: 'Сабаил', city: 'Baku', listingCount: 1, avgPrice: 950000 },
  { id: 'BADAMDAR', slug: 'badamdar', nameAz: 'Badamdar', nameEn: 'Badamdar', nameRu: 'Бадамдар', city: 'Baku', listingCount: 1, avgPrice: 420000 },
  { id: 'GENCE', slug: 'gence', nameAz: 'Gəncə', nameEn: 'Ganja', nameRu: 'Гянджа', city: 'Ganja', listingCount: 1, avgPrice: 95000 },
];

export const MOCK_INQUIRIES: Inquiry[] = [
  {
    id: 'i1',
    propertyId: 'p1',
    name: 'Leyla Məmmədova',
    email: 'leyla@example.com',
    phone: '+994501112233',
    message: 'Bu mənzil haqqında ətraflı məlumat almaq istəyirəm.',
    status: 'NEW',
    createdAt: '2025-06-24T14:00:00Z',
    updatedAt: '2025-06-24T14:00:00Z',
    property: MOCK_PROPERTIES[0],
  },
  {
    id: 'i2',
    propertyId: 'p3',
    name: 'Kamran Əliyev',
    email: 'kamran@example.com',
    phone: '+994502223344',
    message: 'Villaya baxış planlaşdırmaq istəyirəm.',
    status: 'VIEWING',
    createdAt: '2025-06-23T10:00:00Z',
    updatedAt: '2025-06-24T09:00:00Z',
    property: MOCK_PROPERTIES[2],
  },
  {
    id: 'i3',
    propertyId: 'p2',
    name: 'Aynur Quliyeva',
    email: 'aynur@example.com',
    phone: '+994503334455',
    message: 'Kirayə müddəti haqqında sualım var.',
    status: 'CONTACTED',
    createdAt: '2025-06-22T16:00:00Z',
    updatedAt: '2025-06-23T11:00:00Z',
    property: MOCK_PROPERTIES[1],
  },
];

export const MOCK_DASHBOARD: DashboardData = {
  stats: {
    totalListings: 8,
    activeListings: 8,
    totalInquiries: 24,
    newInquiries: 5,
    closedDeals: 3,
    conversionRate: 12.5,
    totalSalesValue: 3285000,
    avgPrice: 410625,
    inquiriesByStatus: {
      NEW: 5,
      CONTACTED: 4,
      VIEWING: 3,
      NEGOTIATING: 2,
      CLOSED: 3,
      REJECTED: 7,
    },
    listingsByType: { SALE: 6, RENT: 2 },
  },
  heatmap: [
    { district: 'NARIMANOV', districtName: 'Nərimanov', listingCount: 2, inquiryCount: 8, avgPrice: 285000, intensity: 0.85 },
    { district: 'YASAMAL', districtName: 'Yasamal', listingCount: 2, inquiryCount: 6, avgPrice: 132500, intensity: 0.72 },
    { district: 'XETAI', districtName: 'Xətai', listingCount: 1, inquiryCount: 5, avgPrice: 1250000, intensity: 0.65 },
    { district: 'SEBAIL', districtName: 'Səbail', listingCount: 1, inquiryCount: 4, avgPrice: 950000, intensity: 0.58 },
    { district: 'BADAMDAR', districtName: 'Badamdar', listingCount: 1, inquiryCount: 3, avgPrice: 420000, intensity: 0.45 },
    { district: 'GENCE', districtName: 'Gəncə', listingCount: 1, inquiryCount: 2, avgPrice: 95000, intensity: 0.32 },
  ],
};

export function filterMockProperties(params: {
  listingType?: string;
  propertyType?: string;
  district?: string;
  minPrice?: number;
  maxPrice?: number;
  minRooms?: number;
  maxRooms?: number;
  page?: number;
  limit?: number;
}): { data: Property[]; pagination: { page: number; limit: number; total: number; totalPages: number } } {
  let filtered = MOCK_PROPERTIES.filter((p) => p.status === 'ACTIVE');

  if (params.listingType) filtered = filtered.filter((p) => p.listingType === params.listingType);
  if (params.propertyType) filtered = filtered.filter((p) => p.propertyType === params.propertyType);
  if (params.district) filtered = filtered.filter((p) => p.district === params.district);
  if (params.minPrice) filtered = filtered.filter((p) => Number(p.price) >= params.minPrice!);
  if (params.maxPrice) filtered = filtered.filter((p) => Number(p.price) <= params.maxPrice!);
  if (params.minRooms) filtered = filtered.filter((p) => p.rooms >= params.minRooms!);
  if (params.maxRooms) filtered = filtered.filter((p) => p.rooms <= params.maxRooms!);

  const page = params.page ?? 1;
  const limit = params.limit ?? 20;
  const total = filtered.length;
  const start = (page - 1) * limit;

  return {
    data: filtered.slice(start, start + limit),
    pagination: { page, limit, total, totalPages: Math.ceil(total / limit) },
  };
}

export function getMockProperty(id: string): Property | undefined {
  return MOCK_PROPERTIES.find((p) => p.id === id);
}
